CRUD_Project/advcbv/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('', views.IndexView.as_view()),
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls', namespace='basic_app')),
]

CRUD_Project/basic_app/urls.py
from django.urls import path
from django.conf.urls import url
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    path('',views.SchoolListView.as_view(), name = 'list'),
    path('<int:pk>/',views.SchoolDetailView.as_view(),name='detail'),
    path('create/',views.SchoolCreateView.as_view(),name='create'),
    path('update/<int:pk>/',views.SchoolUpdateView.as_view(),name='update'),
    path('delete/<int:pk>/',views.SchoolDeleteView.as_view(),name='delete'),

]

CRUD_Project/basic_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("basic_app:detail",kwargs={'pk':self.pk})



class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, related_name='students', on_delete = None)

    def __str__(self):
        return self.name

CRUD_Project/basic_app/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (View, TemplateView,
                                  ListView, DetailView,
                                  CreateView,RedirectView,
                                  UpdateView,DeleteView)

from . import models
# Create your views here.



class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School # This is return as school_list

class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School # This is return as school
    template_name = 'basic_app/school_detail.html'

class IndexView(TemplateView):
    template_name = 'index.html'

    '''def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['injectme'] = "Basic Injection"
        return context'''

class SchoolCreateView(CreateView):
    fields = ("name","principal","location")
    model = models.School

class SchoolUpdateView(UpdateView):
    fields = ("name","principal")
    model = models.School

class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy("basic_app:list")

CRUD_Project/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Base Page</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
    <nav>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <ul class="navbar-nav mr-auto">
          <li> <a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools</a> </li>
          <li> <a class="nav-link" href="{% url 'admin:index' %}">Admin</a> </li>
          <li> <a href="#"></a></li>
        </ul>

      </nav>
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>

  </body>
</html>

CRUD_Project/basic_app/templates/basic_app/school_confirm_delete.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}

<h1>Delete {{ school.name}}?</h1>

<form  method="post">
  {% csrf_token %}
  <input type="submit"  class="btn btn-danger" name="" value="Delete">
  <a class="btn btn-warning" href="{% url 'basic_app:detail' pk=school.pk %}">Cancel</a>
</form>

{% endblock %}

CRUD_Project/basic_app/templates/basic_app/school_detail.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}

<div class="jumbotron">
  <h1>Welcome to the School Detail Page</h1>
  <h2>School Details</h2>
  <p>Name: {{school_detail.name}}</p>
  <p>Principal: {{school_detail.principal}}</p>
  <p>Location: {{school_detail.location}}</p>
  <h3>Students:</h3>
  {% for student in school_detail.students.all %}
  <p>{{student.name}}  who is {{student.age}} years old</p>

  {% endfor %}
</div>
<div class="containter">
  <p><a class="btn btn-warning" href="{% url 'basic_app:update' pk=school_detail.pk %}">Update</a></p>
</div>
{% endblock %}

CRUD_Project/basic_app/templates/basic_app/school_form.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}

<h1>
  {% if not form.instance.pk %}
  Create School
  {% else %}
  Update School
  {% endif %}

</h1>
  <form  method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-primary" name="" value="Submit">
  </form>
{% endblock %}

CRUD_Project/basic_app/templates/basic_app/school_list.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}

<h1>Welcome to a list of all the schools!</h1>
<ol>
  {% for school in schools %}
    <h2><li><a href="{{school.id}}">{{school.name}}</a></li></h2>
  {% endfor %}
</ol>

{% endblock %}

CRUD_Project/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Base Page</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
    <nav>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <ul class="nav navbar-nav">
          <li> <a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools</a> </li>
          <li> <a class="nav-link" href="{% url 'admin:index' %}">Admin</a> </li>
          <li> <a href="#"></a></li>
        </ul>

      </nav>
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>

  </body>
</html>

CRUD_Project/templates/index.html
{% extends "base.html" %}

  {% block body_block %}
    <h1>Welcome to the index page!</h1>
    <h2>Here is your injected content: {{ injectme }}</h2>
  {% endblock %}