fourth_project/fourthApp/urls.py
from django.urls import path
from . import views

# Template tagging
app_name = 'fourthApp'

urlpatterns = [
        path('relative', views.relative, name = 'relative'),
        path('other/', views.other, name = 'other'),
]

fourth_project/fourth_project/urls.py
from django.contrib import admin
from django.urls import include, path
from fourthApp import views

urlpatterns = [
    path('', views.index, name = 'index'),
    path('fourthApp/', include('fourthApp.urls')),
    path('admin/', admin.site.urls),
]

fourth_project/fourthApp/models.py
from django.db import models

# Create your models here.

fourth_project/fourthApp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text': 'hello world', 'number':100}
    return render(request, 'fourthApp/index.html', context_dict)

def other(request):
    return render(request, 'fourthApp/other.html')

def relative(request):
    return render(request, 'fourthApp/relative_url_templates.html')

fourth_project/templates/fourthApp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active"><a class="navbar-brand" href="{% url 'index' %}">BRAND</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">ADMIN</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'fourthApp:other' %}">OTHER</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'fourthApp:relative' %}">RELATIVE</a></li>
        </ul>
      </div>
    </nav>

    <div class="container">

      {% block body_block %}
      {% endblock %}
    </div>
  <h1>Welcome to base</h1>
  </body>
</html>

fourth_project/templates/fourthApp/index.html
<!DOCTYPE html>
{% extends "fourthApp/base.html" %}
  {% block body_block%}
    <h1>Welcome to index page</h1>
    <h2>This is an example of template inheritance</h2>
      <h3>{{ text|cut:'world' }}</h3><br>
      <h4>{{ number|add:"99" }}</h4>
    {% endblock %}

fourth_project/templates/fourthApp/other.html
<!DOCTYPE html>
{% extends "fourthApp/base.html" %}
  {% block body_block%}
    <h1>Welcome to other</h1>
    <h2>This is an example of template inheritance</h2>

    {% endblock %}

fourth_project/templates/fourthApp/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
<h1>Welcome to relative</h1>

  <a href="{% url 'fourthApp:other' %}">The Other Page</a>
  <a href="{% url 'admin:index' %}">Admin</a>
  <a href="{% url 'index' %}">Index</a>
  </body>
</html>