fifth_project/fifth_app/urls.py
from django.urls import path
from . import views

app_name = 'fifth_app'

urlpatterns = [
        path('register/', views.register, name = 'register'),
        path('user_login/', views.user_login, name = 'user_login'),
]

fifth_project/fifth_project/urls.py
from django.contrib import admin
from django.urls import include, path
from fifth_app import views

urlpatterns = [
    path('', views.index, name = 'index'),
    path('fifth_app', include('fifth_app.urls')),
    path('logout/', views.user_logout, name = 'logout'),
    path('special/', views.special, name = 'special'),
    path('admin/', admin.site.urls),
]

fifth_project/fifth_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    # additional
    portfolio_site = models.URLField(blank = True)
    profile_pic = models.ImageField(upload_to = 'fifth_app/profile_pic', blank = True)

    def __str__(self):
        return self.user.username

fifth_project/fifth_app/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

fifth_project/fifth_app/views.py
from django.shortcuts import render
from .forms import UserForm, UserProfileInfoForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout

# Create your views here.
def index(request):
    return render(request, 'fifth_app/index.html')

@login_required
def special(request):
    return HttpResponse("You are logged in!")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            register = True

        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'fifth_app/registration.html',
                    {'user_form':user_form,
                    'profile_form': profile_form,
                    'registered': registered})


def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username =  username, password = password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")

        else:
            print("Someone tried to login and failded")
            print("Username:{} and password: {}".format(username, password))
            return HttpResponse("invalid login dtails supplied!")
    else:
        return render(request, 'fifth_app/login.html',{})

fifth_project/templates/fifth_app/basic.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Fifth Project</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light navbar-static-top">
      <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'index' %}">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'admin:index' %}">Admin <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'fifth_app:register' %}">Register</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'fifth_app:user_login' %}">Login</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>
      </div>
  </nav>
  {% block body_block %}
  {% endblock %}
  </body>
</html>

fifth_project/templates/fifth_app/index.html
{% extends 'fifth_app/basic.html'  %}
{% block body_block %}

<div class="jumbotron">
  <h1>Django Level Five</h1>

</div>

{% endblock %}

fifth_project/templates/fifth_app/login.html
{% extends 'fifth_app/basic.html'  %}
{% load staticfiles %}

{% block body_block %}
<div class="jumbotron">
  <h1>Please Login</h1>
  <form  action="{% url 'fifth_app:user_login' %}" method="post">
    {% csrf_token %}
    <label for="username">UserName:</label>
    <input type="text" name="username" value="Enter Username">
<br>
    <label for="password">Password:</label>
    <input type="password" name="password" value="">
    <br>
    <input type="submit" name="" value="Login">


  </form>

</div>

{% endblock %}

fifth_project/templates/fifth_app/registration.html
{% extends 'fifth_app/basic.html'  %}
{% load staticfiles %}

{% block body_block %}

<div class="jumbotron">
  <h1>Django Level Five</h1>
  {% if registered %}
    <h1>Thank you for registering!</h1>
  {% else %}
  <h3>Register Here!</h3>
  <h4>Fill out the form:</h4>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <input type="submit" name="" value="Register">

  </form>

  {% endif %}

</div>

{% endblock %}